# Generated by Django 4.2 on 2024-06-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventari', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exemplars',
            new_name='Exemplar',
        ),
        migrations.RenameModel(
            old_name='Ubicacions',
            new_name='Ubicacio',
        ),
    ]
