# Generated by Django 4.2 on 2024-06-27 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventari', '0002_rename_exemplars_exemplar_rename_ubicacions_ubicacio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplar',
            name='producte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventari.producte'),
        ),
    ]
